import numpy as np
arr=np.array([1,2,3,4,5,6,5,7,8,9,0,2,1,23,43,65,76,32,21,67])
print('Array =',arr,end=' ')
print()
mean=np.mean(arr)
print('Mean =',mean,end=' ')
print()
median=np.median(arr)
print('Median =',median,end=' ')
print()
min=np.amin(arr)
print('min =',min)
print()
max=np.amax(arr)
print('max =',max)
print()
range=np.ptp(arr)
print('Range =',range)
print()
varience=np.var(arr)
print('varience =',varience)
print()
standardDeviation=np.std(arr)
print('Standard deviation =',standardDeviation)